### PR TITLE
fixes issue with non-processed css files

### PR DESCRIPTION
**Pull request by robertaistleitner**
depicted in https://github.com/labaneilers/hashly/issues/28

### CODE REVIEW

**Comment by robertaistleitner** [comment]
i also added a second fix to support image data which is inlined in css

**Comment by labaneilers** [comment]
Thank you Robert! These all look very well done.

**Comment by labaneilers** [comment]
Your fix was important enough I published a new version to npm:
* hashly 0.4.6
* grunt-hashly 0.2.5

**Comment by robertaistleitner** [comment]
Thanks you! 
Really appreciate your work, we're using it with [Hugo](http://www.gohugo.io) static website generator.

It's really a perfect fit for our build toolchain!

**Pull request merged**
