### PR TITLE
Add sourcemap-include-path option

### PR DESCRIPTION
**Pull request by dpolivy**
Adds a new --sourcemap-include-path/sourcemapIncludePath option which is
a boolean. Default value is TRUE, and preserves existing behavior of
including the full absolute (virtual) path to the map file from the base
directory.

Setting the value to FALSE will cause the sourcemap to be written out as
relative to the source file without any path component.

Fixes labaneilers#35

### CODE REVIEW

**Comment by labaneilers** [comment]
Awesome, thanks Dan!

**Comment by dpolivy** [comment]
Thanks! Can you bump version and publish to npm, and update `grunt-hashly` if necessary?

**Comment by labaneilers** [comment]
I've published your changes as hashly 0.5.0 to npm. I think I need to expose the new features as grunt task properties in grunt-hashly before I can publish that. If you were interested in doing that too, that would be amazing. Otherwise, I'll try to do it over the next few days.

**Comment by dpolivy** [comment]
They're already implemented as properties, and I didn't need to modify grunt-hashly to use them. Perhaps the one thing that could be updated is the documentation, as the property names are different from the CLI parameter names. I basically had to figure out a lot of that by looking at the code.

**Comment by labaneilers** [comment]
You're right, it was easy since the properties were just passed through. I'm glad Laban from a couple years ago thought of that so Laban today had it easier.

Updated and published to grunt-hashly 0.3.0

**Comment by labaneilers** [comment]
It is kind of annoying that some of the property names are different than the command line options. I'll consider fixing that in the future.

**Comment by dpolivy** [comment]
Thanks! Definitely a good improvement for the future, though documenting the options is probably sufficient, too :)

**Pull request merged**
